export default sliderImgs [
    {
        key:'1',
        title:'',
        src:'',
        caption:''
    },{
        key:'2',
        title:'',
        src:'',
        caption:''
    },{
        key:'3',
        title:'',
        src:'',
        caption:''
    },{
        key:'4',
        title:'',
        src:'',
        caption:'',
    },
    {
        key:'5',
        title:'',
        src:'',
        caption:''
    }
]